room_id = 7777
chat_buffer = 200
show_room_title = true
show_room_number = true
color_mode = true
show_ship_level = true
show_medal_name = true
show_medal_level = true
show_timestamp = true  # 显示时间戳
# user_agent = ""